name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    permissions:
      contents: read
      packages: write
    uses: deisi-apps-test-afonso-lucas-tfc/platform-ci/.github/workflows/deploy.yml@main
    with:
      targetPort: "3000"
      usePersistence: true
    secrets: inherit
    
    